---
title: "R for Data Science - Syllabus"
author: "Andrea Gilardi"
date: last-modified
date-format: "[Last modified on:] YYYY-MM-DD"
institute: "University of Milano Bicocca - DEMS"
format:
  pdf: 
    cite-method: biblatex
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    biblatexoptions: [style=authoryear-comp, maxcitenames=1, uniquelist=false, sorting=ynt, maxbibnames=99]
page-layout: full
bibliography: syllabus-refs.bib
nocite: |
  @*
---

The objective of this course is to introduce the students to effective and modern tools for data analysis, version control, and development of R packages. All the materials for the lessons can be found at the following link: <https://github.com/agila5/R4DS-PhD-Unimib>.  

# Program

 We will cover the following topics. 

1. The `tidyverse` and some of its most important packages for data manipulation (such as `dplyr`, `tidyr` and `purrr`) (1.5h) [@wickham2023r; @wickham2019welcome]; 
1. Debugging techniques provided by R and Rstudio (e.g. `debug()`, `browser()`, `traceback()`), and `try()`/`tryCatch()`. (1.5h) [@wickham2019advanced];
1. Git and Github: After creating our first git project, we will explore the most important `git` commands (e.g. `clone`, `status`, `push`, `pull`, `merge`, `diff`, ...) either via the shell or an R package (e.g. `usethis`). Then we will review common errors that may occur when dealing with `git` and `Github` and, finally, we will review a powerful tool for (big) data management named `git lfs` (4.5h) [@bryan2023happy; @progit];
1. R packages: We will create our first R package and discuss the most important aspects (e.g. Imports vs Depends vs Suggests or documentation). Finally, I will show you how to upload that R package on github and present the most important tools for collaborative package development (issues, comments, and PR) (4.5h) [@wickham2023rpackages];

# (Tentative) Schedule

The lessons will be held in presence at the DEMS seminar room U7-2062 according to the following calendar: 

- Friday, March 1st, 14:30-17:30;
- Friday, March 8th, 09.00-12:00;
- Friday, March 15st, 09.00-12:00;
- Friday, March 22st, 09.00-12:00;

**Please notice that we are going to have class in a seminar room. Therefore, the students are kindly requested to bring their own laptop to enjoy hands-on coding sessions. Moreover, please try to install [R](https://cran.rstudio.com/) and [Rstudio](https://posit.co/download/rstudio-desktop/) before the beginning of the lessons. Any version of those two software is ok. If you have any doubt, feel free to contact me (`andrea.gilardi@polimi.it`).**

# Prerequisites

The students are expected to be already familiar with the basics of computer programming (e.g. for-loops, if-clauses, ...) and the R language. If you want to briefly recall the most important topics, I would recommend reading the first few chapters of @de2013r. 

# Final exam

The students will be divided into two groups, each one consisting of at least two people. The two groups are expected to work together to develop a project that consists of two parts: 

1. Exploratory Data Analysis (EDA) with the Tidyverse. You will be required to analyse a given dataset and answer a set of questions;
1. Create an R package that answers a simple statistical problem, providing the necessary testing and documentation. 

The detailed assignments for the two parts will be uploaded on the webpage of the course before the end of the term. More details will be provided during the classes. 

\newrefcontext[sorting=nty]
